name: Production Server Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Install SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.PROD_DEPLOY_SSH_SECRET }}
                  known_hosts: "just-a-placeholder-so-we-dont-get-errors"

            - name: Adding Known Hosts
              run: ssh-keyscan -H ${{ secrets.PROD_DEPLOY_SSH_HOST }} >> ~/.ssh/known_hosts

            - name: Deploy with Git Pull
              run: ssh ${{ secrets.PROD_DEPLOY_SSH_USER }}@${{ secrets.PROD_DEPLOY_SSH_HOST }} 'cd ${{ secrets.PROD_DEPLOY_DIRECTORY }} && ./deploy.sh'
